language: node_js

node_js:
- '8'

cache:
  directories:
  - node_modules

after_success:
- bash <(curl -s https://codecov.io/bash)

script:
- npm run build
- npm run test:coverage
- npm run lint

deploy:
  provider: npm
  email: software@pod-point.com
  api_key:
    secure: XTtGW749GidSA8FInKHaJKdKryLyl6pLysJllh26H23uK8jnDoZ8fvrwkwWGznR+56r84ReOer+TVeDsYHwXMfgOBv62v9ez3n5Vi50iIj4S1xqqoaPxeav14jZirzaT4/i8L//67vk37fs01J2M60ENg9lsmWWsc5dnI6OTywzPh0lNKb/ZIE5/Agc5aJu7oWnl9ynSYd6/vnQv+FnGbDo+vc20eVzoEA2SO8dv0I13oZYwFJbz/RXBHCCiz1rVGWyeQAU86JB/aOe4D6hLVsVF97Br7Su+7VjI/+B8mrr7ioD6l/tjv8HhS+Z9gsqBHCpICzzrqjlwMu0mIOgMZy5IX8s/J6yBDb5wNncmoibefS9BVZahrl+QDhZ5FpM5k9F27JBRlEPEinJ+sr3idHfFGH1iKJBlGeeilP1E+1l3J6T3toIKKR4GucmBCHex4o7UwZjtyO5Vm1MiGxvQGybsJexqrjrEkyCc0lLF8hT/IYwCzYqcdGAHrEVZEeENUEaXM5RU+k8gzV1rwf3oAzoJ41o9X8m3UsvCtTjF5ftTPqJYsmrizGCTBabk6Es2K6lTOPw3djQ0yDmrZZ2p/F/XBszW8181tSuNFZ0F0Kh9pQSH98BY4vu+5YZyaxJ+E0lrBSRkzAA/e2eTYenAGkx2s5th7JhD7RG0muQVq0Y=
  on:
    tags: true
    repo: Pod-Point/typescript
  skip_cleanup: true
