language: node_js

node_js:
- '8'

cache:
  directories:
  - node_modules

after_success:
- bash <(curl -s https://codecov.io/bash)

script:
- npm run lint
- npm run build
- npm run test:coverage

deploy:
  provider: npm
  email: software@pod-point.com
  api_key:
    secure: VabPi5wBuxHa7d2M01o44LrE3udX/cgmTSHia0nGL4PRCl9AujxPj5fsMCNJRbC1Z4ZW6hEnSbICW6fTNXi7x2WXs6xlqCYukDVP8W5yCJtC0GWN7BRH9fH2V9r+521Mmo+BWm7xVRXEhCb7fr7D/PAr5toqSCwPJ6ikItDoAVURoW0U+jNKcI7dcQllxBNdYstWFB7H1XZUru5ZZwzKuJxUmRxKOf7KSM3St2tek7nMxYifVNYSFUTnRuP5/34dyXktHCY5UasvXQj1T0FFlO5/ENYjkppeXxTo8ewhNcF62MEDzJ3Jr5HHKPoApnesveHxWHO/Ix7o1rZZkB+PmoZndqjw9Xgb6KfO8FV1eg44A+WlJphcjF4M7bDt6B5nE8Kha6HiXNtlsxoZM/h2tNs8x1x5nTF3BQucJQc8EhePryaKpruTeWREJpb+V54GX11/7ajlOELHaeg9WTAb0Jrvag9F5wAYJgh9YH3chVvwWlLsVTgFferLKFY6b/Jorh9QllxxUDIsAdQrW4tYQ62TYuxStcEev3Q6esJQCjlpHlrq0l/NPXslz4fGbADwQkKja71GMPOTQobM5YhfPTV9t8AuQslOQdWzT9jsppYfUzprNy9Hj3Sr/6IJ5xOwqhtq2yw3e6kVaR3ozrfaZErluL7wkxs4txtR0AfoOWQ=
  on:
    tags: true
    repo: Pod-Point/typescript
  skip_cleanup: true
